Sponsored transactions.

diff --git a/.github/workflows/release-sponsored-txs-docker.yml b/.github/workflows/release-sponsored-txs-docker.yml
--- a/.github/workflows/release-sponsored-txs-docker.yml
+++ b/.github/workflows/release-sponsored-txs-docker.yml
@@ -35,11 +35,15 @@ jobs:
         run: |
           export FRONTEND_VERSION=$(jq -r .version sponsoredTransactions/frontend/package.json)
           export BACKEND_VERSION=$(yq .package.version sponsoredTransactions/backend/Cargo.toml)
-          export FULL_IMAGE_TAG="${{ env.REGISTRY }}/concordium/$IMAGE_NAME:$FRONTEND_VERSION-$BACKEND_VERSION"
+          export VERSION=$FRONTEND_VERSION-$BACKEND_VERSION
+          export FULL_IMAGE_TAG="${{ env.REGISTRY }}/concordium/$IMAGE_NAME:$VERSION"
           echo "::notice FULL_IMAGE_TAG=${FULL_IMAGE_TAG}"
           # Make sure the image does not exist. Abort if we can retrieve any metadata.
           if docker manifest inspect ${FULL_IMAGE_TAG} > /dev/null; then
              echo "::error ${FULL_IMAGE_TAG} already exists"
+             exit 1
+          elif [ ! "${{ github.ref_name }}" = "sponsored-transactions/${VERSION}" ]; then
+             echo "::error Expected tag ${EXPECTED_TAG} does not match the version ${VERSION}."
              exit 1
           else
              # Store the full image tag into a tag variable for the following step.
